### ISSUE TITLE
Messaging (Utils?) Controller

### ISSUE THREAD

**Issue by wip-abramson** [wip-abramson/aries-basic-controller-python#18]
Extract messaging capability from connections controller into it's own file

**Comment by wip-abramson** [comment]
@lohanspies you also mentioned ability to use decorators. Be interested to hear how we need to adapt the calls to achieve this.

**Comment by lohanspies** [comment]
Hi @wip-abramson, see this document for some decorator examples https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0011-decorators/README.md

We are specifically interested in the ~attach decorator that will allow us to attach/embed a message inside a basic message. Look at this RFC https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0017-attachments/README.md
