### ISSUE TITLE
Exctract agent configuration variable into env file

### ISSUE THREAD

**Issue by wip-abramson** [wip-abramson/aries-basic-controller-python#6]
Or similar.

The controller should be as generic as possible so anyone can configure it for their agent running anywhere.

**Comment by lohanspies** [comment]
Added .env file to extract sensitive information from repo into .env file

**Comment by wip-abramson** [comment]
I can't see this Lohan. Did you push?

**Comment by lohanspies** [comment]
Just pushed the changes. Closing issue again.
